Mozambique
peopledoc/workalendar pull request #542
Opened 2020-09-02 14:19 UTC by mr-shovel

added Mozambique calendar
added tests
updated readme
updated changelog (did not know what to fill in with the (#) part

2020-09-02 15:03 UTC, brunobord requested changes
Overall, this contribution is very good, tests and all!
There are a couple of items to make it pixel perfect. If you need some help, I'll surely be available.

I'm glad that a new African country is about to be added to Workalendar!

2020-09-02 15:03 UTC, brunobord commented on README.rst
> +* Mozambique
please move "Mozambique" in the list so it's going to keep the alphabetical order.

2020-09-02 16:48 UTC, mr-shovel commented
Fixed your comments

2020-09-03 07:40 UTC, ewjoachim commented
Hey :)

I think you have updated the **project**'s gitignore file.
What @brunobord suggested was to setup your **own** personal gitignore file, which would allow not needing every project you work on to make a special case for people with this IDE.

Here's the command you can run:
```console
$ echo .vscode > ~/.gitignoreglobal
$ git config --global core.excludesfile ~/.gitignoreglobal
```

2020-09-03 08:05 UTC, mr-shovel commented
@ewjoachim @brunobord  Thanks for the remarks, learned a thing again today! Anything else needs resolving?

2020-09-03 08:09 UTC, ewjoachim commented
I'm still seeing a diff on the .gitignore file. Is it intended?

(Thanks a lot for the contribution by the way)

2020-09-03 08:22 UTC, mr-shovel commented
You're welcome:) I've removed the .vscode line from the gitignore. the .vscode folder should still be excluded.

2020-09-03 08:28 UTC, ewjoachim approved these changes

2020-09-04 09:50 UTC, brunobord approved these changes
:rocket: :mozambique:

2020-09-04 09:50 UTC, merged

2020-09-04 14:21 UTC, brunobord commented
Mozambique calendar is now available through PyPI:

* https://pypi.org/project/workalendar/11.0.0/
* https://github.com/peopledoc/workalendar/releases/tag/11.0.0

Happy upgrading!